"""time zone update

Revision ID: 65a77213da2b
Revises: 9498f11e599e
Create Date: 2025-06-14 12:59:38.378633

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '65a77213da2b'
down_revision = '9498f11e599e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
