"""added mixin

Revision ID: 9498f11e599e
Revises: 95fda25d2b01
Create Date: 2025-06-13 15:34:26.856933

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9498f11e599e'
down_revision = '95fda25d2b01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Get current timestamp for default values
    from datetime import datetime
    from datetime import timezone
    now = datetime.now(timezone.utc)

    # -- PERMISSION TABLE --
    with op.batch_alter_table('permission', schema=None) as batch_op:
        # First add columns as nullable
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by', sa.Uuid(), nullable=True))
    
    # Update existing rows with default values
    op.execute("UPDATE permission SET created_at = '{}', updated_at = '{}'".format(now, now))
    
    # Then alter columns to be NOT NULL
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.alter_column('created_at', nullable=False)
        batch_op.alter_column('updated_at', nullable=False)
        batch_op.drop_index(batch_op.f('ix_permission_id'))

    # -- ROLE TABLE --
    with op.batch_alter_table('role', schema=None) as batch_op:
        # First add columns as nullable
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by', sa.Uuid(), nullable=True))
    
    # Update existing rows with default values
    op.execute("UPDATE role SET created_at = '{}', updated_at = '{}'".format(now, now))
    
    # Then alter columns to be NOT NULL
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('created_at', nullable=False)
        batch_op.alter_column('updated_at', nullable=False)
        batch_op.drop_index(batch_op.f('ix_role_id'))

    # -- USER TABLE --
    with op.batch_alter_table('user', schema=None) as batch_op:
        # First add columns as nullable
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_by', sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
        batch_op.add_column(sa.Column('profile_image', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    
    # Update existing rows with default values
    op.execute("UPDATE \"user\" SET created_at = '{}', updated_at = '{}', full_name = ''".format(now, now))
    
    # Then alter columns to be NOT NULL
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at', nullable=False)
        batch_op.alter_column('updated_at', nullable=False) 
        batch_op.alter_column('full_name', nullable=False)
        batch_op.drop_index(batch_op.f('ix_user_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)
        batch_op.drop_column('profile_image')
        batch_op.drop_column('full_name')
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_id'), ['id'], unique=False)
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permission_id'), ['id'], unique=False)
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###