"""Add LeaveRequest model and update User, Employee for relationships

Revision ID: 95fda25d2b01
Revises: d98004b08cc8
Create Date: 2025-06-07 17:21:18.679130

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # Added import for sqlmodel types


# revision identifiers, used by Alembic.
revision = '95fda25d2b01'
down_revision = 'd98004b08cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaverequest',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('review_comments', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leaverequest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leaverequest_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaverequest_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaverequest_reviewed_by_user_id'), ['reviewed_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leaverequest_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaverequest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leaverequest_status'))
        batch_op.drop_index(batch_op.f('ix_leaverequest_reviewed_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_leaverequest_id'))
        batch_op.drop_index(batch_op.f('ix_leaverequest_employee_id'))

    op.drop_table('leaverequest')
    # ### end Alembic commands ###
