"""Add fields for advanced user management to User model

Revision ID: c17e70829bbc
Revises: 6f07b075b7dd
Create Date: 2025-06-07 09:37:32.705374

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # Added import for sqlmodel types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c17e70829bbc'
down_revision = '6f07b075b7dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cake_orders')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_email_verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('email_verification_token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_verification_token_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('password_reset_token', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
        batch_op.add_column(sa.Column('password_reset_token_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_locked_out', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('lockout_until', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_email_verification_token'), ['email_verification_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_password_reset_token'), ['password_reset_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_password_reset_token'))
        batch_op.drop_index(batch_op.f('ix_user_email_verification_token'))
        batch_op.drop_column('lockout_until')
        batch_op.drop_column('is_locked_out')
        batch_op.drop_column('failed_login_attempts')
        batch_op.drop_column('password_reset_token_expires_at')
        batch_op.drop_column('password_reset_token')
        batch_op.drop_column('email_verification_token_expires_at')
        batch_op.drop_column('email_verification_token')
        batch_op.drop_column('is_email_verified')

    op.create_table('cake_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cake_description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('delivery_address', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('delivery_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('order_status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('price', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('cake_orders_pkey'))
    )
    # ### end Alembic commands ###
