"""Add HR models: Department, Designation, Employee

Revision ID: d98004b08cc8
Revises: c17e70829bbc
Create Date: 2025-06-07 13:16:11.006101

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # Added import for sqlmodel types


# revision identifiers, used by Alembic.
revision = 'd98004b08cc8'
down_revision = 'c17e70829bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_department_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_department_name'), ['name'], unique=True)

    op.create_table('designation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('designation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_designation_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_designation_title'), ['title'], unique=True)

    op.create_table('employee',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('job_title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('department_id', sa.Uuid(), nullable=True),
    sa.Column('designation_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['designation_id'], ['designation.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_designation_id'), ['designation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_employee_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_user_id'))
        batch_op.drop_index(batch_op.f('ix_employee_id'))
        batch_op.drop_index(batch_op.f('ix_employee_email'))
        batch_op.drop_index(batch_op.f('ix_employee_designation_id'))
        batch_op.drop_index(batch_op.f('ix_employee_department_id'))

    op.drop_table('employee')
    with op.batch_alter_table('designation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_designation_title'))
        batch_op.drop_index(batch_op.f('ix_designation_id'))

    op.drop_table('designation')
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_name'))
        batch_op.drop_index(batch_op.f('ix_department_id'))

    op.drop_table('department')
    # ### end Alembic commands ###
